### ISSUE TITLE
EIPFS_INDEXER_SQS_ARN - document good value to use locally

### ISSUE THREAD

**Issue by gobengo** [web3-storage/w3infra#130]
I wanted to do a test deploy of this to test against access-api, but when I run `npm start` I see `Error: Missing env var: EIPFS_INDEXER_SQS_ARN`

I see that env var requirements was added here https://github.com/web3-storage/w3infra/pull/129

Can we:
* make this environment variable not required when running locally?
* or
  * include a good default for this var in `/.env.tpl`
  * document in the README how to product this variable

**Comment by vasco-santos** [comment]
We should either make not required or use staging in `.env.tpl`. For better testing maybe add to template. 
Thoughts?

**Comment by vasco-santos** [comment]
@gobengo I needed to add a URL now. So also added to env.tpl as I suggested here.
