### ISSUE TITLE
store/add returned presigned url should have size in signature to be validated

### ISSUE THREAD

**Issue by vasco-santos** [web3-storage/w3infra#213]
See https://github.com/web3-storage/w3infra/blob/main/upload-api/buckets/car-store.js#L59-L83

This is also a blocker for https://github.com/web3-storage/w3up/issues/827

**Comment by olizilla** [comment]
The url signer takes the `PutObjectCommand` as input, which includes the expected `content-length` as a parameter. 

https://github.com/web3-storage/w3infra/blob/2c279cd77dcb51a7bb9f4ed60193dda2447a6087/upload-api/buckets/car-store.js#L61-L73

My recollection is this was sufficient to ensure it was part of the signature. What suggests it is not working as expected?

**Comment by olizilla** [comment]
note that you can't hoist `x-amz-checksum-sha256` from an http header to a UrlSearchParam as s3 **only** recognises it as a header. Hence it is included in the `unhoistableHeaders` config.

**Comment by olizilla** [comment]
For context, the PR where we added content-length enforcement goes into detail https://github.com/web3-storage/w3infra/pull/66

**Comment by olizilla** [comment]
oh no. We moved the testing s3 content-length and checksum enforcement to `w3up` and changed it from an integration test against minio (which at least strives for conformance with s3) to a mocked out unit test.

https://github.com/web3-storage/w3up/blob/d868265369ec146f9155102cec8985d954768220/packages/upload-api/test/car-store-bucket.js#L31-L32

We need to add integrations tests back to this repo. We should probably have a test that hits an actual deployment on s3, but i'd settle for re-instating the minio tests for now.

**Comment by olizilla** [comment]
It's OK! we import the tests from `w3up` and run them against a `minio` based context. So our content-length and checksum enforcement tests are run and passing here

>  ✔ service › store › store/add should create a presigned url that can only PUT a payload with the right length (3.2s)

see: https://github.com/web3-storage/w3infra/actions/runs/5592850292/job/15148999911#step:6:42

**Comment by olizilla** [comment]
Closing as it does not appear to be an issue. Re-open if we find evidence to the contrary
