### ISSUE TITLE
Rename repo? Decouple repo? this is not upload-api

### ISSUE THREAD

**Issue by vasco-santos** [web3-storage/w3infra#50]
![writes-pipeline](https://user-images.githubusercontent.com/7295071/204264346-cf26a7f3-8c55-431a-be26-4d88cdf035d1.jpg)

**Comment by gobengo** [comment]
wait this isn't the upload-api?

**Comment by vasco-santos** [comment]
We sat together and decided to move this way

# Today

- web3-storage/w3infra
    - upload-api
    - upload-db
    - carpark
    - satnav
    - eventbus
    - replicator
    - ucan-stream

# Tomorrow

- w3protocol
    - upload-client  
    - upload-api
    - upload-api-cf

- w3infra
    - http-gateway
    - upload-db
    - carpark
    - satnav
    - eventbus
    - replicator
    - ucan-stream
